#!/bin/bash
# Brendan W. Crowell - crowellb@uw.edu
export NETCDFHOME=/usr/share
export PATH=/home/crowellb/Desktop/GMT4.5.9/bin:$PATH
## DECLARE YOUR VARIABLES HERE ##
#################################
  SCALE=15            
  LONMIN=-74 ; LONMAX=-68 # Longitude range of plots
  LATMIN=-37 ; LATMAX=-26 # Latitude range of plots
  NAME=illapel_stations; #Name of input file
#################################
##### make map of slip deficit rate (VelPhi)
rm $NAME.eps
gmtset BASEMAP_TYPE plain PLOT_DEGREE_FORMAT D:F ANNOT_FONT_SIZE_PRIMARY 16 LABEL_FONT_SIZE 16 LABEL_OFFSET 0.05i
gmtset HEADER_FONT_SIZE 16 HEADER_OFFSET -0.1c PAGE_ORIENTATION portrait PAPER_MEDIA A3
makecpt -Cseis -T0/6/1 -D -I > tmp.cpt

psbasemap -R$LONMIN/$LONMAX/$LATMIN/$LATMAX -JM$SCALE -Ba2f1::WeSn -Y1.4i   -K  > $NAME.eps
pscoast -R$LONMIN/$LONMAX/$LATMIN/$LATMAX -J -Ba1f0.5::WeSn -Z5 -Na -S186/236/253 -Lf-73/-18.5/0/100+l -Df -W -O -K  >> $NAME.eps
psxy illapel_150s.txt -Ctmp.cpt -M -L -Wblack -R -J  -O -K  >> $NAME.eps 
pscoast -R -J -Na -Df -O -W -K  >> $NAME.eps
awk '{if ($2 == '150') print $3, $4, $5*100, $6*100, 0, 0, 0 }' illapel_optimal_slipfits.txt | psvelo -R -J -L -Se0.05/0.95/0 -A0.06/0.15/0.12 -O -K -Wblack -Gred  >> $NAME.eps 
awk '{if ($2 == '150') print $3, $4, $8*100, $9*100, 0, 0, 0 }' illapel_optimal_slipfits.txt | psvelo -R -J -L -Se0.05/0.95/0 -A0.06/0.15/0.12 -O -K -Wblack -Ggrey  >> $NAME.eps 
echo -70.81 -19.7 38 0.09 36 93.36 8.33 -73 -21 GPS| psmeca -Sa1.0 -Gred -R -J -O -K -C >> $NAME.eps
echo -70.81 -19.7 21.6 355 15 106 8.2 -73 -20 GlobalCMT| psmeca -Sa1.0 -R -J -O -K -C >> $NAME.eps
psscale -O -D16/5/10/1  -Ctmp.cpt >> $NAME.eps
#echo "-70.81 -19.7" | psxy -R -J -O -K -Sa0.4 -Ggreen -Wblack >> $NAME.eps
#echo "-71.621 -19.59" | psxy -R -J -O -Sa0.4 -Gred -Wblack >> $NAME.eps





